theme: jekyll-theme-minimal
title: [Fabio Massacci Personal Web page]
logo: /images/Fabio-Massacci-2020.jpg
description: [PhD in Computer Science, MSc in Computer Engineering, Master in International Relations.<BR> I am chair of Foundational and Experimental Security at Vrije Universiteit Amsterdam, The Netherlands. I’m also part-time professor at the University of Trento, Italy.]
show_downloads: true
google_analytics:
layout: default
homepage: http://www.massacci.org
name: "jekyll-theme-minimal"
version: "0.0.1"
authors: ["Fabio Massacci"]
