theme: jekyll-theme-minimal
title: [Fabio Massacci Personal Web page]
logo: [/images/Fabio-Massacci-2020.jpg]
description: [Chair of Foundational and Experimental Security at Vrije Universiteit Amsterdam. Part-time professor at University of Trento.]
show_downloads: false
google_analytics:
layout: default
homepage: http://www.massacci.org
name: "jekyll-theme-minimal"
version: "0.0.1"
authors: ["Fabio Massacci"]
