theme: jekyll-theme-minimal
title: ["Fabio Massacci"]
logo: ["/images/Fabio-Massacci-2020.jpg"]
description: ["Personal web page"]
show_downloads: false
google_analytics:
layout: default
homepage: ["http://www.massacci.org"]
name: "jekyll-theme-minimal"
version: "0.0.1"
authors: ["Fabio Massacci"]
